name: Generate Snake Game

on:
  schedule: # Agenda para gerar uma nova animação diariamente
    - cron: "0 0 * * *"
  workflow_dispatch: # Permite execução manual

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      - name: Push generated files to the repository
        uses: EndBug/add-and-commit@v9
        with:
          author_name: "GitHub Action"
          author_email: "action@github.com"
          message: "chore: update snake game"
          add: "dist/*"

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: snake-game
          path: dist/github-snake.svg
