name: Generate Snake Animation

on:
  # Executa automaticamente a cada 24 horas
  schedule:
    - cron: "0 */24 * * *" 
  
  # Permite executar manualmente
  workflow_dispatch:
  
  # Executa a cada push na branch master
  push:
    branches:
      - master

jobs:
  generate:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      # Gera a animação da cobra com o gráfico de contribuições
      - name: Generate github-contribution-grid-snake.svg
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ EliaxZen }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
          
      # Envia os arquivos SVG e GIF para a branch `output`
      - name: Push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
